package com.bkc.model;
// Generated 4 May, 2017 10:18:30 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CropCategoryDetails generated by hbm2java
 */
@Entity
@Table(name = "cropCategoryDetails", catalog = "agroMgnt")
public class CropCategoryDetails implements java.io.Serializable {

	private Integer id;
	private String cropName;
	private String cropHindiName;
	private String categoryName;
	private String categoryHindiName;

	public CropCategoryDetails() {
	}

	public CropCategoryDetails(String cropName, String cropHindiName, String categoryName, String categoryHindiName) {
		this.cropName = cropName;
		this.cropHindiName = cropHindiName;
		this.categoryName = categoryName;
		this.categoryHindiName = categoryHindiName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cropName", nullable = false, length = 50)
	public String getCropName() {
		return this.cropName;
	}

	public void setCropName(String cropName) {
		this.cropName = cropName;
	}

	@Column(name = "cropHindiName", nullable = false, length = 50)
	public String getCropHindiName() {
		return this.cropHindiName;
	}

	public void setCropHindiName(String cropHindiName) {
		this.cropHindiName = cropHindiName;
	}

	@Column(name = "categoryName", nullable = false, length = 50)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "categoryHindiName", nullable = false, length = 50)
	public String getCategoryHindiName() {
		return this.categoryHindiName;
	}

	public void setCategoryHindiName(String categoryHindiName) {
		this.categoryHindiName = categoryHindiName;
	}

}
