package com.bkc.model;
// Generated 24 Apr, 2017 12:05:35 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FertilizersDealers generated by hbm2java
 */
@Entity
@Table(name = "Fertilizers_Dealers", catalog = "Farmersportal")
public class FertilizersDealers implements java.io.Serializable {

	private Integer sno;
	private String state;
	private String district;
	private String block;
	private String nameOfDealer;
	private String address;
	private String contact;
	private String validity;
	private String product;
	private Float lat;
	private Float lon;

	public FertilizersDealers() {
	}

	public FertilizersDealers(String state, String district, String block, String nameOfDealer, String address,
			String contact, String validity, String product, Float lat, Float lon) {
		this.state = state;
		this.district = district;
		this.block = block;
		this.nameOfDealer = nameOfDealer;
		this.address = address;
		this.contact = contact;
		this.validity = validity;
		this.product = product;
		this.lat = lat;
		this.lon = lon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)

	@Column(name = "SNo", unique = true, nullable = false)
	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	@Column(name = "State", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "District", length = 100)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "Block", length = 100)
	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	@Column(name = "NameOfDealer", length = 512)
	public String getNameOfDealer() {
		return this.nameOfDealer;
	}

	public void setNameOfDealer(String nameOfDealer) {
		this.nameOfDealer = nameOfDealer;
	}

	@Column(name = "Address", length = 1024)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Contact", length = 200)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "Validity", length = 100)
	public String getValidity() {
		return this.validity;
	}

	public void setValidity(String validity) {
		this.validity = validity;
	}

	@Column(name = "Product", length = 8000)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "lat", precision = 12, scale = 0)
	public Float getLat() {
		return this.lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

	@Column(name = "lon", precision = 12, scale = 0)
	public Float getLon() {
		return this.lon;
	}

	public void setLon(Float lon) {
		this.lon = lon;
	}

}
