package com.bkc.model;
// Generated 4 May, 2017 12:51:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MandiDetails generated by hbm2java
 */
@Entity
@Table(name = "mandiDetails", catalog = "MandiOilRates")
public class MandiDetails implements java.io.Serializable {

	private Integer id;
	private String mandi;
	private String state;
	private float lat;
	private float lon;

	public MandiDetails() {
	}

	public MandiDetails(String mandi, String state, float lat, float lon) {
		this.mandi = mandi;
		this.state = state;
		this.lat = lat;
		this.lon = lon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mandi", nullable = false, length = 50)
	public String getMandi() {
		return this.mandi;
	}

	public void setMandi(String mandi) {
		this.mandi = mandi;
	}

	@Column(name = "state", nullable = false, length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "lat", nullable = false, precision = 10, scale = 7)
	public float getLat() {
		return this.lat;
	}

	public void setLat(float lat) {
		this.lat = lat;
	}

	@Column(name = "lon", nullable = false, precision = 10, scale = 7)
	public float getLon() {
		return this.lon;
	}

	public void setLon(float lon) {
		this.lon = lon;
	}

}
