package com.bkc.model;
// Generated 24 Apr, 2017 12:05:35 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PesticideDealerProductDetailId generated by hbm2java
 */
@Embeddable
public class PesticideDealerProductDetailId implements java.io.Serializable {

	private int dealerId;
	private int sno;

	public PesticideDealerProductDetailId() {
	}

	public PesticideDealerProductDetailId(int dealerId, int sno) {
		this.dealerId = dealerId;
		this.sno = sno;
	}

	@Column(name = "Dealer_id", nullable = false)
	public int getDealerId() {
		return this.dealerId;
	}

	public void setDealerId(int dealerId) {
		this.dealerId = dealerId;
	}

	@Column(name = "SNo", nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PesticideDealerProductDetailId))
			return false;
		PesticideDealerProductDetailId castOther = (PesticideDealerProductDetailId) other;

		return (this.getDealerId() == castOther.getDealerId()) && (this.getSno() == castOther.getSno());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDealerId();
		result = 37 * result + this.getSno();
		return result;
	}

}
