package com.bkc.model;
// Generated 24 Apr, 2017 12:05:35 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PesticideDealers generated by hbm2java
 */
@Entity
@Table(name = "Pesticide_Dealers", catalog = "Farmersportal")
public class PesticideDealers implements java.io.Serializable {

	private Integer srN;
	private String dealerName;
	private String stateDistrictBlock;
	private String address;
	private String mobile;
	private String licenseId;
	private String licenseValidity;
	private String description;
	private Float lat;
	private Float lon;

	public PesticideDealers() {
	}

	public PesticideDealers(String dealerName, String stateDistrictBlock, String address, String mobile,
			String licenseId, String licenseValidity, String description, Float lat, Float lon) {
		this.dealerName = dealerName;
		this.stateDistrictBlock = stateDistrictBlock;
		this.address = address;
		this.mobile = mobile;
		this.licenseId = licenseId;
		this.licenseValidity = licenseValidity;
		this.description = description;
		this.lat = lat;
		this.lon = lon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SrN", unique = true, nullable = false)
	public Integer getSrN() {
		return this.srN;
	}

	public void setSrN(Integer srN) {
		this.srN = srN;
	}

	@Column(name = "DealerName", length = 100)
	public String getDealerName() {
		return this.dealerName;
	}

	public void setDealerName(String dealerName) {
		this.dealerName = dealerName;
	}

	@Column(name = "State_District_Block", length = 100)
	public String getStateDistrictBlock() {
		return this.stateDistrictBlock;
	}

	public void setStateDistrictBlock(String stateDistrictBlock) {
		this.stateDistrictBlock = stateDistrictBlock;
	}

	@Column(name = "Address", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "LicenseId", length = 300)
	public String getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(String licenseId) {
		this.licenseId = licenseId;
	}

	@Column(name = "LicenseValidity", length = 20)
	public String getLicenseValidity() {
		return this.licenseValidity;
	}

	public void setLicenseValidity(String licenseValidity) {
		this.licenseValidity = licenseValidity;
	}

	@Column(name = "Description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "lat", precision = 12, scale = 0)
	public Float getLat() {
		return this.lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

	@Column(name = "lon", precision = 12, scale = 0)
	public Float getLon() {
		return this.lon;
	}

	public void setLon(Float lon) {
		this.lon = lon;
	}

}
