package com.bkc.model;
// Generated 24 Apr, 2017 12:05:35 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeedDealersId generated by hbm2java
 */
@Embeddable
public class SeedDealersId implements java.io.Serializable {

	private String dealerId;
	private String bcod;

	public SeedDealersId() {
	}

	public SeedDealersId(String dealerId, String bcod) {
		this.dealerId = dealerId;
		this.bcod = bcod;
	}

	@Column(name = "Dealer_id", nullable = false, length = 10)
	public String getDealerId() {
		return this.dealerId;
	}

	public void setDealerId(String dealerId) {
		this.dealerId = dealerId;
	}

	@Column(name = "BCod", nullable = false, length = 20)
	public String getBcod() {
		return this.bcod;
	}

	public void setBcod(String bcod) {
		this.bcod = bcod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeedDealersId))
			return false;
		SeedDealersId castOther = (SeedDealersId) other;

		return ((this.getDealerId() == castOther.getDealerId()) || (this.getDealerId() != null
				&& castOther.getDealerId() != null && this.getDealerId().equals(castOther.getDealerId())))
				&& ((this.getBcod() == castOther.getBcod()) || (this.getBcod() != null && castOther.getBcod() != null
						&& this.getBcod().equals(castOther.getBcod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDealerId() == null ? 0 : this.getDealerId().hashCode());
		result = 37 * result + (getBcod() == null ? 0 : this.getBcod().hashCode());
		return result;
	}

}
