package com.bkc.model;
// Generated 24 Apr, 2017 12:05:35 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SeedDealers generated by hbm2java
 */
@Entity
@Table(name = "Seed_Dealers", catalog = "Farmersportal")
public class SeedDealers implements java.io.Serializable {

	private SeedDealersId id;
	private String companyName;
	private String contactPerson;
	private String address;
	private String districtBlock;
	private String phone;
	private String websiteEmail;
	private String licenseNo;
	private String validUpto;
	private String licenseAuthority;
	private Float lon;
	private Float lat;

	public SeedDealers() {
	}

	public SeedDealers(SeedDealersId id, String contactPerson) {
		this.id = id;
		this.contactPerson = contactPerson;
	}

	public SeedDealers(SeedDealersId id, String companyName, String contactPerson, String address, String districtBlock,
			String phone, String websiteEmail, String licenseNo, String validUpto, String licenseAuthority, Float lon,
			Float lat) {
		this.id = id;
		this.companyName = companyName;
		this.contactPerson = contactPerson;
		this.address = address;
		this.districtBlock = districtBlock;
		this.phone = phone;
		this.websiteEmail = websiteEmail;
		this.licenseNo = licenseNo;
		this.validUpto = validUpto;
		this.licenseAuthority = licenseAuthority;
		this.lon = lon;
		this.lat = lat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dealerId", column = @Column(name = "Dealer_id", nullable = false, length = 10)),
			@AttributeOverride(name = "bcod", column = @Column(name = "BCod", nullable = false, length = 20)) })
	public SeedDealersId getId() {
		return this.id;
	}

	public void setId(SeedDealersId id) {
		this.id = id;
	}

	@Column(name = "CompanyName", length = 500)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "ContactPerson", nullable = false, length = 100)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "Address", length = 120)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "District_Block", length = 120)
	public String getDistrictBlock() {
		return this.districtBlock;
	}

	public void setDistrictBlock(String districtBlock) {
		this.districtBlock = districtBlock;
	}

	@Column(name = "Phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Website_Email", length = 120)
	public String getWebsiteEmail() {
		return this.websiteEmail;
	}

	public void setWebsiteEmail(String websiteEmail) {
		this.websiteEmail = websiteEmail;
	}

	@Column(name = "LicenseNo", length = 80)
	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	@Column(name = "ValidUpto", length = 20)
	public String getValidUpto() {
		return this.validUpto;
	}

	public void setValidUpto(String validUpto) {
		this.validUpto = validUpto;
	}

	@Column(name = "LicenseAuthority", length = 100)
	public String getLicenseAuthority() {
		return this.licenseAuthority;
	}

	public void setLicenseAuthority(String licenseAuthority) {
		this.licenseAuthority = licenseAuthority;
	}

	@Column(name = "lon", precision = 12, scale = 0)
	public Float getLon() {
		return this.lon;
	}

	public void setLon(Float lon) {
		this.lon = lon;
	}

	@Column(name = "lat", precision = 12, scale = 0)
	public Float getLat() {
		return this.lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

}
