package com.bkc.model;
// default package
// Generated 20 Apr, 2017 10:58:25 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRegisteredCropId generated by hbm2java
 */
@Embeddable
public class UserRegisteredCropId implements java.io.Serializable {

	private String phoneNo;
	private int cropId;

	public UserRegisteredCropId() {
	}

	public UserRegisteredCropId(String phoneNo, int cropId) {
		this.phoneNo = phoneNo;
		this.cropId = cropId;
	}

	@Column(name = "phoneNo", nullable = false)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "cropId", nullable = false)
	public int getCropId() {
		return this.cropId;
	}

	public void setCropId(int cropId) {
		this.cropId = cropId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRegisteredCropId))
			return false;
		UserRegisteredCropId castOther = (UserRegisteredCropId) other;

		return (this.getPhoneNo() == castOther.getPhoneNo()) && (this.getCropId() == castOther.getCropId());
	}

	public int hashCode() {
		int result = 17;

		//result = 37 * result + this.getPhoneNo();
		result = 37 * result + this.getCropId();
		return result;
	}

}
