package com.bkc.model;
// default package
// Generated 20 Apr, 2017 10:58:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRegisteredCrop generated by hbm2java
 */
@Entity
@Table(name = "userRegisteredCrop", catalog = "agroMgnt")
public class UserRegisteredCrop implements java.io.Serializable {

	private UserRegisteredCropId id;
	private Date sowingDate;
	private Date lastUpdatedTime;

	public UserRegisteredCrop() {
	}

	public UserRegisteredCrop(UserRegisteredCropId id, Date sowingDate, Date lastUpdatedTime) {
		this.id = id;
		this.sowingDate = sowingDate;
		this.lastUpdatedTime = lastUpdatedTime;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "phoneNo", column = @Column(name = "phoneNo", nullable = false)),
			@AttributeOverride(name = "cropId", column = @Column(name = "cropId", nullable = false)) })
	public UserRegisteredCropId getId() {
		return this.id;
	}

	public void setId(UserRegisteredCropId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sowingDate", nullable = false, length = 10)
	public Date getSowingDate() {
		return this.sowingDate;
	}

	public void setSowingDate(Date sowingDate) {
		this.sowingDate = sowingDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastUpdatedTime", nullable = false, length = 19)
	public Date getLastUpdatedTime() {
		return this.lastUpdatedTime;
	}

	public void setLastUpdatedTime(Date lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}

}
